server:
  port: 9000

spring:
  profiles:
    active: local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  messages:
    basename: messages
    encoding: UTF-8
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
  jpa:
    hibernate:
      hbm2ddl.auto: create-drop
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2-db/yongsblog
    username: sa
    password:
    driver-class-name: org.h2.Driver
decorator:
  datasource:
    p6spy:
      enable-logging: true
