server:
  port: 9000

spring:
  profiles:
    active: local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  messages:
    basename: messages
    encoding: UTF-8
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2-db/yongsblog
    username: sa
    password:
    driver-class-name: org.h2.Driver

decorator:
  datasource:
    # p6spy 설정 적용
    p6spy:
      enable-logging: true
      multiline: true
logging:
  level:
    org.hibernate.SQL: info
  config: classpath:log4j2.yml
